-- schema.sql
-- Create database and players table for npgolf
CREATE DATABASE IF NOT EXISTS npgolf CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE npgolf;

CREATE TABLE IF NOT EXISTS players (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL UNIQUE,
  sex CHAR(1) DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  quota DECIMAL(5,2) DEFAULT NULL,
  fedex_points INT DEFAULT 0,
  tournaments_played INT DEFAULT 0,
  prize_money DECIMAL(12,2) DEFAULT 0.00,
  password VARCHAR(255) DEFAULT NULL,
  role VARCHAR(20) DEFAULT 'player',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quota (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  player_id INT UNSIGNED NOT NULL,
  date_1 DATE DEFAULT NULL,
  points_1 DECIMAL(5,2) DEFAULT NULL,
  date_2 DATE DEFAULT NULL,
  points_2 DECIMAL(5,2) DEFAULT NULL,
  date_3 DATE DEFAULT NULL,
  points_3 DECIMAL(5,2) DEFAULT NULL,
  date_4 DATE DEFAULT NULL,
  points_4 DECIMAL(5,2) DEFAULT NULL,
  date_5 DATE DEFAULT NULL,
  points_5 DECIMAL(5,2) DEFAULT NULL,
  date_6 DATE DEFAULT NULL,
  points_6 DECIMAL(5,2) DEFAULT NULL,
  date_7 DATE DEFAULT NULL,
  points_7 DECIMAL(5,2) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
  INDEX idx_player_id (player_id)
);

CREATE TABLE IF NOT EXISTS skins_quota (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  player_id INT UNSIGNED NOT NULL,
  date_1 DATE DEFAULT NULL,
  points_1 DECIMAL(5,2) DEFAULT NULL,
  date_2 DATE DEFAULT NULL,
  points_2 DECIMAL(5,2) DEFAULT NULL,
  date_3 DATE DEFAULT NULL,
  points_3 DECIMAL(5,2) DEFAULT NULL,
  date_4 DATE DEFAULT NULL,
  points_4 DECIMAL(5,2) DEFAULT NULL,
  date_5 DATE DEFAULT NULL,
  points_5 DECIMAL(5,2) DEFAULT NULL,
  date_6 DATE DEFAULT NULL,
  points_6 DECIMAL(5,2) DEFAULT NULL,
  date_7 DATE DEFAULT NULL,
  points_7 DECIMAL(5,2) DEFAULT NULL,
  date_8 DATE DEFAULT NULL,
  points_8 DECIMAL(5,2) DEFAULT NULL,
  date_9 DATE DEFAULT NULL,
  points_9 DECIMAL(5,2) DEFAULT NULL,
  date_10 DATE DEFAULT NULL,
  points_10 DECIMAL(5,2) DEFAULT NULL,
  date_11 DATE DEFAULT NULL,
  points_11 DECIMAL(5,2) DEFAULT NULL,
  date_12 DATE DEFAULT NULL,
  points_12 DECIMAL(5,2) DEFAULT NULL,
  date_13 DATE DEFAULT NULL,
  points_13 DECIMAL(5,2) DEFAULT NULL,
  date_14 DATE DEFAULT NULL,
  points_14 DECIMAL(5,2) DEFAULT NULL,
  date_15 DATE DEFAULT NULL,
  points_15 DECIMAL(5,2) DEFAULT NULL,
  date_16 DATE DEFAULT NULL,
  points_16 DECIMAL(5,2) DEFAULT NULL,
  date_17 DATE DEFAULT NULL,
  points_17 DECIMAL(5,2) DEFAULT NULL,
  date_18 DATE DEFAULT NULL,
  points_18 DECIMAL(5,2) DEFAULT NULL,
  date_19 DATE DEFAULT NULL,
  points_19 DECIMAL(5,2) DEFAULT NULL,
  date_20 DATE DEFAULT NULL,
  points_20 DECIMAL(5,2) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
  INDEX idx_player_id (player_id)
);

CREATE TABLE IF NOT EXISTS course (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  address VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hole (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  course_id INT UNSIGNED NOT NULL,
  hole_number TINYINT UNSIGNED NOT NULL,
  mens_distance INT UNSIGNED NOT NULL,
  mens_par TINYINT UNSIGNED NOT NULL,
  mens_handicap TINYINT UNSIGNED NOT NULL,
  ladies_distance INT UNSIGNED NOT NULL,
  ladies_par TINYINT UNSIGNED NOT NULL,
  ladies_handicap TINYINT UNSIGNED NOT NULL,
  UNIQUE KEY unique_course_hole (course_id, hole_number),
  FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tournament (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL,
  first_tee_time TIME DEFAULT NULL,
  course_id INT UNSIGNED NOT NULL,
  number_of_holes TINYINT UNSIGNED NOT NULL DEFAULT 18,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE RESTRICT,
  INDEX idx_date (date),
  INDEX idx_course_id (course_id)
);

CREATE TABLE IF NOT EXISTS scores (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  entered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  tournament_id INT UNSIGNED NOT NULL,
  player_id INT UNSIGNED NOT NULL,
  hole_id INT UNSIGNED NOT NULL,
  score TINYINT UNSIGNED NOT NULL,
  quota DECIMAL(5,2) DEFAULT NULL,
  foursome_group VARCHAR(50) DEFAULT NULL,
  FOREIGN KEY (tournament_id) REFERENCES tournament(id) ON DELETE CASCADE,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
  FOREIGN KEY (hole_id) REFERENCES hole(id) ON DELETE CASCADE,
  INDEX idx_tournament_id (tournament_id),
  INDEX idx_player_id (player_id),
  INDEX idx_hole_id (hole_id),
  UNIQUE KEY unique_tournament_player_hole (tournament_id, player_id, hole_id)
);
