-- Change points fields to INT in quota table
ALTER TABLE quota 
  MODIFY COLUMN points_1 INT DEFAULT NULL,
  MODIFY COLUMN points_2 INT DEFAULT NULL,
  MODIFY COLUMN points_3 INT DEFAULT NULL,
  MODIFY COLUMN points_4 INT DEFAULT NULL,
  MODIFY COLUMN points_5 INT DEFAULT NULL,
  MODIFY COLUMN points_6 INT DEFAULT NULL,
  MODIFY COLUMN points_7 INT DEFAULT NULL;
