# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bee49696f5225dcabc1caa173e8dd0eed6bf429283fc1341e596dc2aa9d0536eabefd28abdd37dd49ed41d2a492a9cfc1fc2ee6c65b75a03081c7765d5797ec

test:
  secret_key_base: d744653e45daca08a7a95130c818295d29879c75433cd58c183e51e5ed951ff65fdb712d6ea6d5d94ccaeb19afb329465fe9faba3826a0eff19370821362f3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
