#!/usr/bin/env node
require('dotenv').config();
const mysql = require('mysql2/promise');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

async function main() {
  const host = process.env.DB_HOST || '127.0.0.1';
  const port = process.env.DB_PORT ? Number(process.env.DB_PORT) : 3306;
  const rootUser = process.env.DB_USER || 'root';
  const rootPass = process.env.DB_PASS || '';
  const dbName = process.env.DB_NAME || 'npgolf';

  if (!rootUser || !rootPass) {
    console.error('Root DB credentials are required in .env to create the app user (DB_USER/DB_PASS)');
    process.exit(1);
  }

  // generate a secure random password
  const password = crypto.randomBytes(16).toString('base64url');
  const appUser = 'npgolf_app';
  const appHost = '%';

  const conn = await mysql.createConnection({
    host, port, user: rootUser, password: rootPass, multipleStatements: true
  });

  try {
    console.log(`Creating/altering user ${appUser}@${appHost} for database ${dbName}`);

    // Create user if not exists, otherwise alter to set password (works across MySQL versions)
    // Use parameterized queries for the password only; identifiers are fixed strings here.
    await conn.query(`CREATE USER IF NOT EXISTS '${appUser}'@'${appHost}' IDENTIFIED BY ?`, [password]);
    // Ensure the password is updated if user exists on older versions
    try {
      await conn.query(`ALTER USER '${appUser}'@'${appHost}' IDENTIFIED BY ?`, [password]);
    } catch (err) {
      // Some MySQL configs disallow ALTER USER; ignore and continue
    }

    // Grant minimal privileges
    await conn.query(`GRANT SELECT, INSERT, UPDATE ON ${dbName}.* TO '${appUser}'@'${appHost}'`);
    await conn.query('FLUSH PRIVILEGES');

    // Write .env.local with the app user credentials (do not overwrite existing .env)
    const outPath = path.join(process.cwd(), '.env.local');
    const lines = [];
    // preserve common DB settings from current env if present
    lines.push(`# Local env file generated by scripts/create_app_user.js`);
    lines.push(`DB_HOST=${host}`);
    lines.push(`DB_PORT=${port}`);
    lines.push(`DB_NAME=${dbName}`);
    lines.push(`DB_USER=${appUser}`);
    lines.push(`DB_PASS=${password}`);
    lines.push('');

    if (fs.existsSync(outPath)) {
      console.log('.env.local already exists — backing up to .env.local.bak');
      fs.copyFileSync(outPath, outPath + '.bak');
    }

    fs.writeFileSync(outPath, lines.join('\n'));
    console.log(`Wrote ${outPath} — update your local .env or use this file for local runs.`);
    console.log(`Generated credentials: user=${appUser} password=${password}`);
  } catch (err) {
    console.error('Failed to create app user:', err);
    process.exitCode = 1;
  } finally {
    await conn.end();
  }
}

main().catch(err => { console.error(err); process.exit(1); });
